name: Validaci贸n HTML y CSS

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener c贸digo
        uses: actions/checkout@v4

      # Validaci贸n de HTML
      - name: Instalar y validar HTML con HTMLHint
        run: |
          npm install -g htmlhint
          htmlhint "**/*.html"

      # Validaci贸n de CSS
      - name: Instalar y validar CSS con Stylelint
        run: |
          npm install -g stylelint stylelint-config-standard
          stylelint "css/**/*.css"
